# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot = {
    extraModprobeConfig = "options nvidia-drm modeset=1";

    initrd = {
      # wait for hdd to be ready
      postDeviceCommands = "sleep 1s";

      kernelModules = [
        "nvidia"
      ];

      availableKernelModules = [
        "ohci_pci" "ehci_pci" "pata_amd" "sata_nv" "usb_storage" "usbhid" "sd_mod"
      ];
    };

    kernelModules = [ "kvm-amd" ];

    kernelParams = [ "quiet" ];

    loader.grub = {
      enable = true;
      version = 2;
      device = "/dev/disk/by-uuid/eaf30e64-0a90-447f-b53d-1598fe46a8a9";
    };

    # clear /tmp on every boot
    cleanTmpDir = true;
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/eaf30e64-0a90-447f-b53d-1598fe46a8a9";
      fsType = "btrfs";
      options = [ "subvol=@nixos" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/eaf30e64-0a90-447f-b53d-1598fe46a8a9";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/eaf30e64-0a90-447f-b53d-1598fe46a8a9";
      fsType = "btrfs";
      options = [ "subvol=@tmp" ];
    };

  fileSystems."/data" =
    { device = "/dev/disk/by-uuid/eaf30e64-0a90-447f-b53d-1598fe46a8a9";
      fsType = "btrfs";
      options = [ "subvol=@data" ];
    };

  swapDevices = [
      { device = "/dev/disk/by-uuid/d73d2b09-0981-4a48-8199-ed956a51bc57"; }
    ];

  powerManagement.cpuFreqGovernor = "ondemand";
}
