# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot = {

    loader.grub = {
          enable = true;
          version = 2;
          device = "/dev/disk/by-id/wwn-0x50014ee1002d4ea2";

          # memtest86.enable = true;
    };

    initrd = {
      availableKernelModules = [
        "ohci_pci" "ehci_pci" "pata_amd" "sata_nv" "usb_storage" "usbhid" "sd_mod"
      ];

      kernelModules = [
        "nouveau"
      ];
    };

    kernelModules = [
      "kvm-amd"
      "nouveau"
    ];
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a2850c65-e8ff-426e-9879-726bb224603c";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/941fa838-9e0a-4f43-a772-7cb8d651fada";
      fsType = "ext4";
    };

  fileSystems."/data" =
    { device = "/dev/disk/by-uuid/eaf30e64-0a90-447f-b53d-1598fe46a8a9";
      fsType = "btrfs";
      options = [ "subvol=@data" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/eaf30e64-0a90-447f-b53d-1598fe46a8a9";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  swapDevices = [
    # { device = "/dev/disk/by-uuid/05aecd11-7a37-4a6b-bafd-2500e7c62a13"; }
    ];

  nix.maxJobs = lib.mkDefault 2;
}
